verifier_app/models.py
from flask.ext.login import UserMixin, AnonymousUserMixin
from flask.ext.sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class DBStoredValue(db.Model):
    name = db.Column(db.String(), unique=True, primary_key=True)
    val = db.Column(db.String())

    def __init__(self, key, value):
        self.name = str(key)
        self.val = str(value)

    def __repr__(self):
        return '<DBStoredValue {0}: {1}>'.format(self.name, self.val)

    def get_key(self):
        return self.name

    def get_value(self):
        return self.val


class EmailEntry(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    address = db.Column(db.String())
    validity = db.Column(db.Boolean())
    processed = db.Column(db.Boolean())
    spam = db.Column(db.Boolean())

    def __init__(self, address):
        self.address = address

    def __repr__(self):
        if self.validity:
            result = '<EmailEntry %s (valid)>' % self.address
        else:
            result = '<EmailEntry %s (invalid)>' % self.address

        return result

    def set_validity(self, value):
        self.validity = bool(value)

    def is_vaild(self):
        return self.validity

    def set_processed(self, value):
        self.processed = bool(value)

    def is_processed(self):
        return self.processed

    def set_spam(self, value):
        self.spam = bool(value)

    def has_spam(self):
        return self.spam

    def get_address(self):
        return self.address


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String())
    password = db.Column(db.String())

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, value):
        return check_password_hash(self.password, value)

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User %r>' % self.username

verifier_app/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms import validators

from .models import User


class LoginForm(Form):
    username = TextField(u'Username', validators=[validators.required()])
    password = PasswordField(u'Password', validators=[validators.optional()])

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password')
            return False

        return True

verifier_app/__init__.py
#! ../env/bin/python

from flask import Flask
from webassets.loaders import PythonLoader as PythonAssetsLoader
from verifier_app import assets
from verifier_app.models import db
from verifier_app.controllers.main import main
from verifier_app.extensions import (
    cache,
    assets_env,
    debug_toolbar,
    login_manager,
    celery_client
)


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. verifier_app.settings.ProdConfig
    """

    app = Flask(__name__)

    app.config.from_object(object_name)

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    login_manager.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # register our blueprints
    app.register_blueprint(main)

    return app

verifier_app/controllers/main.py
import time
import os
from email import encoders

from email.MIMEBase import MIMEBase
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from flask import Blueprint, render_template, flash, request, redirect, url_for, jsonify
from flask.ext.login import login_user, logout_user, login_required

from verifier_app.extensions import cache
from verifier_app.filters import *
from verifier_app.forms import LoginForm
from verifier_app.models import User, EmailEntry, db, DBStoredValue
from verifier_app.tasks import verify_address

main = Blueprint('main', __name__)
thread = None


@main.route('/')
@cache.cached(timeout=1000)
@login_required
def home():
    return render_template('index.html')


@main.route('/check', methods=["GET", "POST"])
@login_required
def check():
    if request.method == 'POST':
        # Setting initial options to pass to 'result.html' template
        options = {}

        # Getting file with addresses
        uploaded_file = request.files['inputAddressFile']

        # And reading its content
        file_data = uploaded_file.read()
        # If there's content
        if file_data:
            # Then fill list with addresses
            address_list = file_data.split('\n')
            # And strip whitespaces
            address_list = [x.strip().lower() for x in address_list if "@" in x]

            # Saving initial length
            options["initial_len"] = len(address_list)
            store_value_in_db("initial_len", len(address_list))

            # Removing duplicates
            address_list = set(address_list)

            # And saving length without duplicates
            options["nodups_len"] = len(address_list)
            store_value_in_db("nodups_len", len(address_list))
        else:
            # Otherwise show an alert
            flash("Address list is empty", "danger")
            # And return
            return render_template('index.html')

        # Getting keywords file
        uploaded_file = request.files['inputKeywordFile']
        file_data = uploaded_file.read()
        keyword_list = []
        # Reading its data
        if file_data:
            keyword_list = file_data.split('\n')
            keyword_list = [word.strip().lower() for word in keyword_list]
        # If no data was transmitted, flash info alert
        else:
            flash("You didn't specify keywords list", "info")
        store_value_in_db("keyword_list_len", len(keyword_list))

        # The same with domains file
        uploaded_file = request.files['inputDomainFile']
        file_data = uploaded_file.read()
        domain_list = []
        if file_data:
            domain_list = file_data.split('\n')
            domain_list = [word.strip().lower() for word in domain_list]
        else:
            flash("You didn't specify domains list", "info")
        store_value_in_db("domain_list_len", len(domain_list))

        # And the same with MX records file
        uploaded_file = request.files['inputMXFile']
        file_data = uploaded_file.read()
        mx_list = []
        if file_data:
            mx_list = file_data.split('\n')
            mx_list = [word.strip().lower() for word in mx_list]
        else:
            flash("You didn't specify MX records list", "info")
        store_value_in_db("mx_list_len", len(mx_list))

        # At last, TOR usage
        use_tor = bool(request.form.getlist('useTOR'))
        if use_tor:
            print __file__
        else:
            flash("You don't use TOR network", "info")
        store_value_in_db("use_tor", use_tor)

        # And its rotation
        try:
            exit_node_rotation = int(request.form.getlist('exitNodeRotationNum')[0])
        except IndexError:
            exit_node_rotation = 0
        store_value_in_db("exit_node_rotation", exit_node_rotation)

        address_list = check_syntax(address_list)
        options["after_syntax_len"] = len(address_list)
        store_value_in_db("after_syntax_len", len(address_list))

        address_list = filter_keywords(address_list, keyword_list)
        options["after_keywords_len"] = len(address_list)
        store_value_in_db("after_keywords_len", len(address_list))

        address_list = filter_domains(address_list, domain_list)
        options["after_domains_len"] = len(address_list)
        store_value_in_db("after_domains_len", len(address_list))

        # Deleting previous data
        EmailEntry.query.delete()
        db.session.commit()

        for address in address_list:
            new_entry = EmailEntry(address)
            new_entry.set_processed(False)
            new_entry.set_validity(False)
            db.session.add(new_entry)
        while True:
            try:
                db.session.commit()
                break
            except Exception as e:
                print "During DB commit: " + str(e)
                time.sleep(1)
        for entry in EmailEntry.query.all():
            verify_address.delay(entry.id, mx_list, use_tor, 0)

        return redirect("/result")


def store_value_in_db(name, val):
    new_row = DBStoredValue(name, val)
    db.session.merge(new_row)
    db.session.commit()


def get_value_from_db(name):
    return db.session. \
        query(DBStoredValue). \
        filter_by(name=name). \
        first(). \
        get_value()


@main.route("/result")
@login_required
def show_result_page():
    options = {}

    return render_template("result.html", **options)


@main.route("/status")
@login_required
def get_tool_status():
    while True:
        try:
            result = {}
            total_count = EmailEntry.query.count()
            processed_count = EmailEntry.query.filter_by(processed=True).count()
            valid_count = EmailEntry.query.filter_by(validity=True).count()

            result["total_count"] = str(total_count)
            result["processed_count"] = str(processed_count)
            result["valid_count"] = str(valid_count)

            result['progress_overall'] = (float(processed_count) / total_count) * 100
            result['progress_valid'] = (float(valid_count) / total_count) * 100

            result["initial_len"] = int(get_value_from_db("initial_len"))
            result["nodups_len"] = int(get_value_from_db("nodups_len"))
            result["after_syntax_len"] = int(get_value_from_db("after_syntax_len"))
            result["after_keywords_len"] = int(get_value_from_db("after_keywords_len"))
            result["after_domains_len"] = int(get_value_from_db("after_domains_len"))
            result["keyword_list_len"] = int(get_value_from_db("keyword_list_len"))
            result["domain_list_len"] = int(get_value_from_db("domain_list_len"))
            result["mx_list_len"] = int(get_value_from_db("mx_list_len"))
            result["use_tor"] = bool(get_value_from_db("use_tor"))

            return jsonify(result)
        except Exception as e:
            print "During status fetch: " + str(e)


@main.route("/restart_worker")
@login_required
def restart_worker():
    os.system("ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9")
    time.sleep(5)
    os.system("nohup celery worker -A verifier_app.tasks --loglevel=INFO --concurrency=12 --purge > celery.out &")
    time.sleep(5)
    status = dict()
    status["success"] = True
    return jsonify(status)


@main.route("/mail_results", methods=["POST"])
@login_required
def mail_results():
    # Mails .txt result to predefined address
    status = dict()

    status["valid_entry_len"] = EmailEntry.query.filter_by(validity=True).count()
    status["spam_entry_len"] = EmailEntry.query.filter_by(spam=True).count()

    with open("result.txt", "wb") as f:
        for valid_entry in EmailEntry.query.filter_by(validity=True):
            f.write("{0}\r\n".format(valid_entry.get_address()))

    with open("spam.txt", "wb") as f:
        for valid_entry in EmailEntry.query.filter_by(spam=True):
            f.write("{0}\r\n".format(valid_entry.get_address()))

    # "From" address built upon AWS instance's public DNS
    from_address = "bot@localhost"
    to_address = request.form["address"]
    status["address"] = to_address

    # Preparing message
    msg = MIMEMultipart()

    msg['From'] = from_address
    msg['To'] = to_address
    msg['Subject'] = "Email addresses verification result"

    body = "Check attachment."

    msg.attach(MIMEText(body, 'plain'))

    # And first attachment
    attachment = open("result.txt", "rb")

    part = MIMEBase('application', 'octet-stream')
    part.set_payload(attachment.read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', "attachment; filename=result.txt")

    msg.attach(part)

    # And spam attachment
    attachment = open("spam.txt", "rb")

    part = MIMEBase('application', 'octet-stream')
    part.set_payload(attachment.read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', "attachment; filename=spam.txt")

    msg.attach(part)

    try:
        # And sending it
        from smtplib import SMTP
        server = SMTP('localhost')
        text = msg.as_string()
        server.sendmail(from_address, to_address, text)
        server.quit()

        status["success"] = True

    except Exception as e:
        status["success"] = False
        print e

    return jsonify(status)


@main.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for(".home"))

    return render_template("login.html", form=form)


@main.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out.", "success")

    return redirect(url_for(".home"))

verifier_app/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        {% block css %}
        {% endblock %}

        <!-- <script src="{{ url_for('static', filename='js/vendor/modernizr.min.js') }}"></script> -->
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Email verification</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
					<li><a href="{{ url_for('.home') }}">Upload data</a></li>
					<li><a href="{{ url_for('.show_result_page') }}">Check progress</a></li>
                    {% if not current_user.is_authenticated() %}
                        <li><a href="{{ url_for('.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('.logout') }}">Logout</a></li>
                    {% endif %}                  
                </ul>
            </div><!--/.nav-collapse -->
        </div>

        <div class="container">
			<div class="col-md-offset-4 col-md-4">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
			</div>
			
            {% block body %}
            {% endblock %}
        </div>

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
        
        {% block js %}
        {% endblock %}
    </body>
</html>

verifier_app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
    {% block js %}
        <script xmlns="http://www.w3.org/1999/html">
            function validateForm() {
                var x = $("input[name=inputAddressFile]").val();
                if (x == null || x == "") {
                    $('#noAddressModal').modal('show')
                    return false;
                }
            }
        </script>
    {% endblock %}

    <div class="modal fade" tabindex="-1" role="dialog" id="noAddressModal" aria-labelledby="gridSystemModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="gridSystemModalLabel">Address list empty</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p>Looks like you forgot to specify address list</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <h1 class="text-center">Start working with tool</h1>
            <hr/>
        </div>
    </div>

    <form enctype="multipart/form-data" method="POST" role="form" action="{{ url_for('main.check') }}"
          onsubmit="return validateForm()">
        <div class="row">
            <div class="col-md-12">
                <h2>Step 1</h2>
                <p>
                <h3>Specify input emails</h3></p>
                <p>You need to import list of email addresses from .txt file. Each address should be on its own
                    line.</p>
                <br/>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="inputAddressFile">Addresses list</label>
                        <input type="file" id="inputAddressFile" name="inputAddressFile">
                        <p class="help-block">Select .txt or .csv file</p>
                    </div>
                </div>

            </div>
        </div>
        <hr/>

        <div class="row">
            <div class="col-md-12">
                <h3>Step 2</h3>
                <p>
                <h3>Specify filters</h3></p>
                <p>Set keyword, domain and MX record lists. Each list should be a .txt file, containing one record per
                    line.</p>
                <br/>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="inputKeywordFile">Keywords list</label>
                        <input type="file" id="inputKeywordFile" name="inputKeywordFile">
                        <p class="help-block">Select .txt file</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="inputDomainFile">Domains list</label>
                        <input type="file" id="inputDomainFile" name="inputDomainFile">
                        <p class="help-block">Select .txt file</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="inputMXFile">MX records list</label>
                        <input type="file" id="inputMXFile" name="inputMXFile">
                        <p class="help-block">Select .txt file</p>
                    </div>
                </div>
            </div>
        </div>
        <hr/>

        <div class="row">
            <div class="col-md-12">
                <h3>Step 3</h3>
                <p>
                <h3>TOR configuration</h3></p>
                <p>Enable or disable working through TOR network. Tool will spawn multiple instances of TOR proxies.</p>
                <br/>
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="useTOR" id="useTOR" checked="true"> Use TOR network
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr/>

        <div class="row">
            <div class="col-md-12">
                <h3>Step 4</h3>
                <p>
                <h3>Let's go</h3></p>
                <p>Start checking! It might take some time for script to proceed all the data. Please, be patient.</p>
                <br/>
                <div class="col-md-4">
                    <div class="form-group">
                        <button type="submit" class="btn btn-default btn-lg">Verify</button>
                    </div>
                </div>
            </div>
        </div>
        <hr/>
    </form>
{% endblock %}

verifier_app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block body %}
	<div class="row">
        <div class="col-md-4 col-md-offset-4">
			<h1 class="text-center">Login</h1>  
            <form role="form" action="{{ url_for('.login') }}" method="post">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

verifier_app/templates/result.html
{% extends "base.html" %}

{% block title %}Results{% endblock %}

{% block js %}
<script>
	function update_progress() {
		status_url = '{{ url_for(".get_tool_status") }}';
		// send GET request to status URL
		$.getJSON(status_url, function( data ) {
			// Show length of initial upload in <p>
			$('#initial_len').text("Initial upload: " + data["initial_len"]);
			
			// Show length after removed duplicates
			$('#nodups_len').text("After removing duplicates: " + 
				data["nodups_len"] + 
				" (" + (data['initial_len'] - data['nodups_len']) + " removed)");
				
			// Show length after syntax check
			$('#after_syntax_len').text("After syntax check: " + 
				data["after_syntax_len"] + 
				" (" + (data['nodups_len'] - data['after_syntax_len']) + " removed)");

			// Show length after keywords filter
			$('#after_keywords_len').text("After keyword filtering: " + 
				data["after_keywords_len"] + 
				" (" + (data['after_syntax_len'] - data['after_keywords_len']) + " removed)");

			// Show length after domains filter
			$('#after_domains_len').text("After domains filtering: " + 
				data["after_domains_len"] + 
				" (" + (data['after_keywords_len'] - data['after_domains_len']) + " removed)");
				
			$("#keyword_list_len").text('Keyword list: ' + data["keyword_list_len"] + ' entries');
			$("#domain_list_len").text('Domain list: ' + data["domain_list_len"] + ' entries');
			$("#mx_list_len").text('MX list: ' + data["mx_list_len"] + ' entries');
			$("#use_tor").text('Using TOR: ' + data["use_tor"]);

			$("#total").text('Total number of entries: ' + data['total_count']);
			$("#processed").text('Numbers of processed entries: ' + data['processed_count']);
			$("#valid").text('Numbers of valid entries: ' + data['valid_count']);

			if (data["active_threads"]==0) {
				$("#progressOverall").css("width", (100 - data['progress_valid']) + "%");
				$("#progressValid").css("width", data['progress_valid'] + "%");
				$("#processed").text('Numbers of processed entries: ' + data['total_count']);
			} else {
				$("#progressOverall").css("width", (data['progress_overall'] - data['progress_valid']) + "%");
				$("#progressValid").css("width", data['progress_valid'] + "%");
			}
						
			if (data['total_count'] != data['processed_count']) {
				setTimeout(function() {
							update_progress();
						}, 5000);
			};
		});
	};
	
	function send_email() {
		$.ajax({
			type: "POST",
			url: '{{ url_for(".mail_results") }}',
			data: $("#email").serialize(),
			success: function(data) {
				if (data["success"]) {
					$("#emailAlertDiv").html(
					'<div class="alert alert-success alert-dismissible fade in" role="alert">' +
						'<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
							'<span aria-hidden="true">×</span>' +
						'</button>' +
						'<strong>Success</strong><br/>' +
						'Mail sent to <strong>' + data["address"] + '</strong>' +
						'<br/>Valid: ' + data["valid_entry_len"] + ', spam: ' + data["spam_entry_len"] +
						'</div>'
					)
				}
				else {
					$("#emailAlertDiv").html(
					'<div class="alert alert-danger alert-dismissible fade in" role="alert">' +
						'<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
							'<span aria-hidden="true">×</span>' +
						'</button>' +
						'<strong>Fail</strong><br/>' +
						'Failed to send message to <strong>' + data["address"] +
					'</strong></div>'
					)
				}
		   }});
	};
	
	update_progress();
</script>
{% endblock %}

{% block body %}

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h1 class="text-center">Verification results</h1><hr/>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Statistic</h3>
			</div>
			<div class="panel-body">
				<p id="initial_len"></p>
				<p id="nodups_len"></p>
				<p id="after_syntax_len"></p>
				<p id="after_keywords_len"></p>
				<p id="after_domains_len"></p>	
				<hr/>
				<p id="keyword_list_len"></p>
				<p id="domain_list_len"></p>
				<p id="mx_list_len"></p>
				<p id="use_tor"></p>
			</div>
		</div>			
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Progress</h3>
			</div>
			<div class="panel-body">
				<p id="total"></p>
				<p id="processed"></p>
				<p id="valid"></p>
				<div class="progress">
					<div class="progress-bar progress-bar-success" style="width: 0%" id="progressValid">
					</div>
					<div class="progress-bar progress-bar" style="width: 0%" id="progressOverall" />
					</div>
				</div>
			</div>
		</div>		
	</div>
</div>
<hr/>


<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<form id="email">
		<div class="input-group">
		  <input type="text" class="form-control" name="address" placeholder="Enter your email...">
		  <span class="input-group-btn">
			<button class="btn btn-default" type="button" id="sendMail" role="button" onclick="send_email()">Send!</button>
		  </span>
		</div>
		</form><!-- /input-group -->
	</div>
</div><hr/>

<div class="row" id="success_alert">
	<div class="col-md-4 col-md-offset-4" id="emailAlertDiv">
	</div>
</div>
{% endblock %}